package MantenedorEmpleado;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import java.sql.ResultSet;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;
/**
 *
 * @author Daniel
 */
public class frmActualizarE extends javax.swing.JFrame {

    /**
     * Creates new form frmActualizarRol
     */
    public frmActualizarE() {
        initComponents();
        this.setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        txtRut = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescripcion = new javax.swing.JTextArea();
        cmdBuscar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jdCF_contratacion = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jdCF_nacimiento = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();
        cmbSexo = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        txtDomicilio = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        cmdAceptar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setName("frmCrearCuenta"); // NOI18N

        jLabel1.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        jLabel1.setText("Nombre del empleado");
        jLabel1.setName("lblNombre"); // NOI18N

        jLabel2.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        jLabel2.setText("Telefono");
        jLabel2.setName("lblTelefono"); // NOI18N

        jLabel3.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        jLabel3.setText("Rut:");
        jLabel3.setName("lblRut"); // NOI18N

        txtNombre.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        txtNombre.setBorder(null);
        txtNombre.setEnabled(false);
        txtNombre.setName("txtNombre"); // NOI18N

        txtTelefono.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        txtTelefono.setBorder(null);
        txtTelefono.setEnabled(false);
        txtTelefono.setName("txtTelefono"); // NOI18N

        txtRut.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        txtRut.setBorder(null);
        txtRut.setName("txtRut"); // NOI18N
        txtRut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRutActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        jLabel5.setText("Descripcion");

        txtDescripcion.setColumns(20);
        txtDescripcion.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        txtDescripcion.setRows(5);
        txtDescripcion.setBorder(null);
        txtDescripcion.setEnabled(false);
        jScrollPane1.setViewportView(txtDescripcion);

        cmdBuscar.setBackground(new java.awt.Color(0, 0, 0));
        cmdBuscar.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        cmdBuscar.setForeground(new java.awt.Color(255, 255, 255));
        cmdBuscar.setText("Buscar");
        cmdBuscar.setBorder(null);
        cmdBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdBuscarActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jLabel8.setText("ACTUALIZAR EMPLEADO");

        jdCF_contratacion.setEnabled(false);

        jLabel4.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        jLabel4.setText("Fecha de Nacimiento");

        jLabel6.setText("Fecha de contratacion");

        jdCF_nacimiento.setEnabled(false);

        jLabel7.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        jLabel7.setText("Sexo");

        cmbSexo.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        cmbSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Femenino" }));
        cmbSexo.setBorder(null);
        cmbSexo.setEnabled(false);

        jLabel9.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        jLabel9.setText("Domicilio");

        txtDomicilio.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        txtDomicilio.setBorder(null);
        txtDomicilio.setEnabled(false);

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));

        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));

        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));

        jSeparator5.setForeground(new java.awt.Color(0, 0, 0));

        jSeparator6.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtRut, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                                    .addComponent(jSeparator1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmdBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel7)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jdCF_contratacion, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jdCF_nacimiento, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(cmbSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(254, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2)
                            .addComponent(jLabel9)
                            .addComponent(jLabel1)
                            .addComponent(jLabel5)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(445, 445, 445))
                            .addComponent(jScrollPane1)
                            .addComponent(txtTelefono)
                            .addComponent(txtDomicilio)
                            .addComponent(jSeparator3)
                            .addComponent(jSeparator4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator2)
                            .addComponent(txtNombre)
                            .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator6))
                        .addGap(0, 26, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addComponent(jLabel8)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtRut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(cmdBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDomicilio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jdCF_nacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jdCF_contratacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        jButton1.setBackground(new java.awt.Color(255, 51, 0));
        jButton1.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Volver");
        jButton1.setBorder(null);
        jButton1.setName("cmdVolver"); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        cmdAceptar.setBackground(new java.awt.Color(0, 0, 255));
        cmdAceptar.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        cmdAceptar.setForeground(new java.awt.Color(255, 255, 255));
        cmdAceptar.setText("Aceptar");
        cmdAceptar.setBorder(null);
        cmdAceptar.setEnabled(false);
        cmdAceptar.setName("cmdAceptar"); // NOI18N
        cmdAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdAceptarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cmdAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(cmdAceptar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtRutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRutActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cmdAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdAceptarActionPerformed
        String RutUsuario = txtRut.getText();
        String nombre = txtNombre.getText();
        String telefono = txtTelefono.getText();
        String descripcion = txtDescripcion.getText();
        String domicilio = txtDomicilio.getText();

        String sexo = cmbSexo.getSelectedItem().toString();

        java.util.Date fechaNacimientoUtil = jdCF_nacimiento.getDate();
        java.util.Date fechaContratacionUtil = jdCF_contratacion.getDate();

        java.sql.Date fechaNacimientoSQL = new java.sql.Date(fechaNacimientoUtil.getTime());
        java.sql.Date fechaContratacionSQL = new java.sql.Date(fechaContratacionUtil.getTime());

        Connection con = Conexion.getConexion();

        if (con != null) {
            try {
                // Comprueba si el RutUsuario ya existe en la tabla usuario
                String consultaExistencia = "SELECT 1 FROM usuario WHERE Rut_Usuario = ?";
                PreparedStatement pstmtExistencia = con.prepareStatement(consultaExistencia);
                pstmtExistencia.setString(1, RutUsuario);
                ResultSet rsExistencia = pstmtExistencia.executeQuery();

                if (rsExistencia.next()) {
                    // El RutUsuario existe en la tabla usuario, por lo que actualizamos los datos en la tabla empleado
                    String consultaActualizacion = "UPDATE empleado SET Nombre = ?, Telefono = ?, Descripcion = ?, Domicilio = ?, F_nacimiento = ?, F_contratacion = ?, Sexo = ? WHERE RutUsuario = ?";
                    PreparedStatement pstmtActualizacion = con.prepareStatement(consultaActualizacion);
                    pstmtActualizacion.setString(1, nombre);
                    pstmtActualizacion.setString(2, telefono);
                    pstmtActualizacion.setString(3, descripcion);
                    pstmtActualizacion.setString(4, domicilio);
                    pstmtActualizacion.setDate(5, fechaNacimientoSQL);
                    pstmtActualizacion.setDate(6, fechaContratacionSQL);
                    pstmtActualizacion.setString(7, sexo);
                    pstmtActualizacion.setString(8, RutUsuario);

                    int filasAfectadas = pstmtActualizacion.executeUpdate();

                    if (filasAfectadas > 0) {
                        JOptionPane.showMessageDialog(null, "Datos actualizados exitosamente.");
                        
                        // Limpia los campos
                    txtNombre.setText("");
                    txtTelefono.setText("");
                    txtDescripcion.setText("");
                    txtDomicilio.setText("");
                    jdCF_nacimiento.setDate(null);
                    jdCF_contratacion.setDate(null);
                    cmbSexo.setSelectedIndex(0);

                    // Habilita los campos
                    txtNombre.setEnabled(false);
                    txtTelefono.setEnabled(false);
                    txtDescripcion.setEnabled(false);
                    txtDomicilio.setEnabled(false);
                    jdCF_nacimiento.setEnabled(false);
                    jdCF_contratacion.setEnabled(false);
                    cmbSexo.setEnabled(false);

                    // Habilita el botón Aceptar
                    cmdAceptar.setEnabled(false);

                    // Habilita el campo txtRut para ingresar un nuevo Rut
                    txtRut.setText(""); // Limpia el campo
                    txtRut.setEnabled(true); // Habilita el campo
                    cmdBuscar.setEnabled(true); // Habilita el botón "Buscar"

                    // Coloca el foco en el campo txtRut
                    txtRut.requestFocus();
                    } else {
                        JOptionPane.showMessageDialog(null, "No se encontró el RutUsuario en la tabla empleado.");
                    }

                    pstmtActualizacion.close();
                } else {
                    JOptionPane.showMessageDialog(null, "El RutUsuario no existe en la tabla usuario.");
                }

                rsExistencia.close();
                pstmtExistencia.close();
                con.close();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Error al actualizar datos: " + ex.toString());
            }
        } else {
            JOptionPane.showMessageDialog(null, "No se pudo establecer la conexión a la base de datos.");
        }
    }//GEN-LAST:event_cmdAceptarActionPerformed

    private void cmdBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdBuscarActionPerformed
        String RutUsuario = txtRut.getText();

        Connection con = Conexion.getConexion();

        if (con != null) {
            try {
                String consulta = "SELECT * FROM empleado WHERE RutUsuario = ?";
                PreparedStatement pstmt = con.prepareStatement(consulta);
                pstmt.setString(1, RutUsuario);

                ResultSet rs = pstmt.executeQuery();

                if (rs.next()) {
                    int numEmpleado = rs.getInt("NumEmpleado");
                    String nombre = rs.getString("Nombre");
                    String telefono = rs.getString("Telefono");
                    String descripcion = rs.getString("Descripcion");
                    String domicilio = rs.getString("Domicilio");
                    java.sql.Date fechaNacimientoSQL = rs.getDate("F_nacimiento");
                    java.sql.Date fechaContratacionSQL = rs.getDate("F_contratacion");
                    String sexo = rs.getString("Sexo");

                    txtNombre.setText(nombre);
                    txtTelefono.setText(telefono);
                    txtDescripcion.setText(descripcion);
                    txtDomicilio.setText(domicilio);

                    if (fechaNacimientoSQL != null) {
                        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
                        String fechaNacimientoStr = dateFormat.format(fechaNacimientoSQL);
                        jdCF_nacimiento.setDate(dateFormat.parse(fechaNacimientoStr));
                    } else {
                        jdCF_nacimiento.setDate(null);
                    }

                    if (fechaContratacionSQL != null) {
                        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
                        String fechaContratacionStr = dateFormat.format(fechaContratacionSQL);
                        jdCF_contratacion.setDate(dateFormat.parse(fechaContratacionStr));
                    } else {
                        jdCF_contratacion.setDate(null);
                    }

                    cmbSexo.setSelectedItem(sexo);

                    String mensaje = "Empleado encontrado:\n" +
                            "Número de Empleado: " + numEmpleado + "\n" +
                            "Nombre: " + nombre;
                    JOptionPane.showMessageDialog(null, mensaje);

                    cmdAceptar.setEnabled(false);

                    // Habilita los campos y botones
                    txtNombre.setEnabled(true);
                    txtTelefono.setEnabled(true);
                    txtDescripcion.setEnabled(true);
                    txtDomicilio.setEnabled(true);
                    jdCF_nacimiento.setEnabled(true);
                    jdCF_contratacion.setEnabled(true);
                    cmbSexo.setEnabled(true);
                    cmdAceptar.setEnabled(true);

                    // Deshabilita el campo txtRut
                    txtRut.setEnabled(false);
                    cmdBuscar.setEnabled(false);

                } else {
                    JOptionPane.showMessageDialog(null, "Empleado no encontrado.");

                    jdCF_nacimiento.setDate(null);
                    jdCF_contratacion.setDate(null);
                    cmbSexo.setSelectedIndex(0);

                    txtNombre.setEnabled(true);
                    txtTelefono.setEnabled(true);
                    txtDescripcion.setEnabled(true);
                    txtDomicilio.setEnabled(true);
                    jdCF_nacimiento.setEnabled(true);
                    jdCF_contratacion.setEnabled(true);
                    cmbSexo.setEnabled(true);
                    cmdAceptar.setEnabled(true);

                    // Habilita el campo txtRut para ingresar un nuevo Rut
                    txtRut.setText(""); // Limpia el campo
                    txtRut.setEnabled(true); // Habilita el campo
                    cmdBuscar.setEnabled(true); // Habilita el botón "Buscar"

                    // Coloca el foco en el campo txtRut
                    txtRut.requestFocus();
                }

                rs.close();
                pstmt.close();
                con.close();
            } catch (SQLException | ParseException ex) {
                JOptionPane.showMessageDialog(null, "Error al buscar empleado: " + ex.toString());
            }
        } else {
            JOptionPane.showMessageDialog(null, "No se pudo establecer la conexión a la base de datos.");
}
      
    }//GEN-LAST:event_cmdBuscarActionPerformed
        
    
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmActualizarE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmActualizarE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmActualizarE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmActualizarE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmActualizarE().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbSexo;
    private javax.swing.JButton cmdAceptar;
    private javax.swing.JButton cmdBuscar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private com.toedter.calendar.JDateChooser jdCF_contratacion;
    private com.toedter.calendar.JDateChooser jdCF_nacimiento;
    private javax.swing.JTextArea txtDescripcion;
    private javax.swing.JTextField txtDomicilio;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtRut;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
