package Main;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import com.toedter.calendar.JDateChooser;
/**
 *
 * @author Daniel
 */
public class frmCrearCuenta extends javax.swing.JFrame {

    /**
     * Creates new form frmCrearCuenta
     */
    public frmCrearCuenta() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        txtRut = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        cmdAceptar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescripcion = new javax.swing.JTextArea();
        cmdBuscar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jdCF_contratacion = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jdCF_nacimiento = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();
        cmbSexo = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        txtDomicilio = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);

        jPanel1.setName("frmCrearCuenta"); // NOI18N

        jLabel1.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        jLabel1.setText("Nombre del empleado");
        jLabel1.setName("lblNombre"); // NOI18N

        jLabel2.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        jLabel2.setText("Telefono");
        jLabel2.setName("lblTelefono"); // NOI18N

        jLabel3.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        jLabel3.setText("Rut:");
        jLabel3.setName("lblRut"); // NOI18N

        txtNombre.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        txtNombre.setEnabled(false);
        txtNombre.setName("txtNombre"); // NOI18N

        txtTelefono.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        txtTelefono.setEnabled(false);
        txtTelefono.setName("txtTelefono"); // NOI18N

        txtRut.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        txtRut.setName("txtRut"); // NOI18N
        txtRut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRutActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(255, 0, 0));
        jButton1.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Volver");
        jButton1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton1.setName("cmdVolver"); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        cmdAceptar.setBackground(new java.awt.Color(0, 0, 255));
        cmdAceptar.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        cmdAceptar.setForeground(new java.awt.Color(255, 255, 255));
        cmdAceptar.setText("Aceptar");
        cmdAceptar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        cmdAceptar.setEnabled(false);
        cmdAceptar.setName("cmdAceptar"); // NOI18N
        cmdAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdAceptarActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        jLabel5.setText("Descripcion");

        txtDescripcion.setColumns(20);
        txtDescripcion.setRows(5);
        txtDescripcion.setEnabled(false);
        jScrollPane1.setViewportView(txtDescripcion);

        cmdBuscar.setBackground(new java.awt.Color(0, 0, 0));
        cmdBuscar.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        cmdBuscar.setForeground(new java.awt.Color(255, 255, 255));
        cmdBuscar.setText("Buscar");
        cmdBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdBuscarActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        jLabel8.setText("Agregar Empleado");

        jdCF_contratacion.setEnabled(false);

        jLabel4.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        jLabel4.setText("Fecha de Nacimiento");

        jLabel6.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        jLabel6.setText("Fecha de contratacion");

        jdCF_nacimiento.setEnabled(false);

        jLabel7.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        jLabel7.setText("Sexo");

        cmbSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Femenino" }));
        cmbSexo.setEnabled(false);

        jLabel9.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        jLabel9.setText("Domicilio");

        txtDomicilio.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        txtDomicilio.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(157, 157, 157))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDomicilio, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtRut, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmdBuscar))
                            .addComponent(jLabel3)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(cmbSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jdCF_contratacion, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtTelefono, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jdCF_nacimiento, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel5)
                            .addComponent(jLabel1)
                            .addComponent(jLabel9)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cmdAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 469, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 18, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel8)
                .addGap(43, 43, 43)
                .addComponent(jLabel3)
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmdBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDomicilio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(2, 2, 2)
                .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jdCF_nacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jdCF_contratacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmdAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(76, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmdAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdAceptarActionPerformed
        
        String RutUsuario = txtRut.getText();
        String nombre = txtNombre.getText();
        String telefono = txtTelefono.getText();
        String descripcion = txtDescripcion.getText();
        String domicilio = txtDomicilio.getText(); 

   
        String sexo = cmbSexo.getSelectedItem().toString();

  
        java.util.Date fechaNacimientoUtil = jdCF_nacimiento.getDate();
        java.util.Date fechaContratacionUtil = jdCF_contratacion.getDate();

   
        java.sql.Date fechaNacimientoSQL = new java.sql.Date(fechaNacimientoUtil.getTime());
        java.sql.Date fechaContratacionSQL = new java.sql.Date(fechaContratacionUtil.getTime());


        Connection con = Conexion.getConexion();

        if (con != null) {
            try {
                String consultaExistencia = "SELECT 1 FROM usuario WHERE Rut_Usuario = ?";
                PreparedStatement pstmtExistencia = con.prepareStatement(consultaExistencia);
                pstmtExistencia.setString(1, RutUsuario);
                ResultSet rsExistencia = pstmtExistencia.executeQuery();

                if (!rsExistencia.next()) {
                    String consultaInsercionUsuario = "INSERT INTO usuario (Rut_Usuario) VALUES (?)";
                    PreparedStatement pstmtInsercionUsuario = con.prepareStatement(consultaInsercionUsuario);
                    pstmtInsercionUsuario.setString(1, RutUsuario);
                    int filasAfectadasUsuario = pstmtInsercionUsuario.executeUpdate();

                    if (filasAfectadasUsuario > 0) {
                        String consultaInsercionEmpleado = "INSERT INTO empleado (RutUsuario, Nombre, Telefono, Descripcion, Domicilio, F_nacimiento, F_contratacion, Sexo, estado) VALUES (?, ?, ?, ?, ?, ?, ?, ?, 'A')";
                        PreparedStatement pstmtInsercionEmpleado = con.prepareStatement(consultaInsercionEmpleado);
                        pstmtInsercionEmpleado.setString(1, RutUsuario);
                        pstmtInsercionEmpleado.setString(2, nombre);
                        pstmtInsercionEmpleado.setString(3, telefono);
                        pstmtInsercionEmpleado.setString(4, descripcion);
                        pstmtInsercionEmpleado.setString(5, domicilio);
                        pstmtInsercionEmpleado.setDate(6, fechaNacimientoSQL); 
                        pstmtInsercionEmpleado.setDate(7, fechaContratacionSQL);
                        pstmtInsercionEmpleado.setString(8, sexo);
                        pstmtInsercionEmpleado.executeUpdate();

                        JOptionPane.showMessageDialog(null, "Datos insertados exitosamente.");
                        txtNombre.setText("");
                        txtTelefono.setText("");
                        txtDescripcion.setText("");
                        txtDomicilio.setText("");
                        jdCF_nacimiento.setDate(null);
                        jdCF_contratacion.setDate(null);
                        cmbSexo.setSelectedIndex(0);

                        txtNombre.setEnabled(false);
                        txtTelefono.setEnabled(false);
                        txtDescripcion.setEnabled(false);
                        txtDomicilio.setEnabled(false);
                        jdCF_nacimiento.setEnabled(false);
                        jdCF_contratacion.setEnabled(false);
                        cmbSexo.setEnabled(false);

                      
                        cmdAceptar.setEnabled(false);

                        
                        txtRut.setText("");
                        txtRut.setEnabled(true); 
                        cmdBuscar.setEnabled(true);

                        
                        txtRut.requestFocus();

                        pstmtInsercionEmpleado.close();
                    } else {
                        JOptionPane.showMessageDialog(null, "Error al insertar RutUsuario en usuario.");
                    }

                    pstmtInsercionUsuario.close();
                } else {
                    JOptionPane.showMessageDialog(null, "El RutUsuario ya existe en la tabla usuario.");
                }

                rsExistencia.close();
                pstmtExistencia.close();
                con.close();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Error al insertar datos: " + ex.toString());
            }
        } else {
            JOptionPane.showMessageDialog(null, "No se pudo establecer la conexión a la base de datos.");
        }
    }//GEN-LAST:event_cmdAceptarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed
    public static boolean validarRut(String rut) {
        // Separar el dígito verificador del resto del RUT
        String rutSinDV = rut.substring(0, rut.length() - 1);
        char dv = rut.charAt(rut.length() - 1);

        // Invertir el RUT sin el dígito verificador
        StringBuilder rutInvertido = new StringBuilder(rutSinDV).reverse();

        int suma = 0;
        int peso = 2;

        // Aplicar el algoritmo Módulo 11
        for (char digito : rutInvertido.toString().toCharArray()) {
            int valor = Character.getNumericValue(digito);
            suma += valor * peso;
            peso = (peso == 7) ? 2 : peso + 1;
        }

        int residuo = 11 - (suma % 11);
        char dvCalculado = (residuo == 11) ? '0' : (residuo == 10) ? 'K' : Character.forDigit(residuo, 10);

        return dv == dvCalculado;
    }
    private void cmdBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdBuscarActionPerformed
        String RutUsuario = txtRut.getText();
        
            Connection con = Conexion.getConexion();

        if (con != null) {
            try {
                // Realiza una consulta para verificar si el RutUsuario existe en la tabla 'empleado'
                String consultaBusquedaEmpleado = "SELECT * FROM empleado WHERE RutUsuario = ?";
                PreparedStatement pstmtBusquedaEmpleado = con.prepareStatement(consultaBusquedaEmpleado);
                pstmtBusquedaEmpleado.setString(1, RutUsuario);
                ResultSet rsEmpleado = pstmtBusquedaEmpleado.executeQuery();

                if (rsEmpleado.next()) {
                    // El empleado existe, muestra sus datos y bloquea los campos
                    txtNombre.setText(rsEmpleado.getString("Nombre"));
                    txtTelefono.setText(rsEmpleado.getString("Telefono"));
                    txtDescripcion.setText(rsEmpleado.getString("Descripcion"));
                    txtDomicilio.setText(rsEmpleado.getString("Domicilio"));
                    jdCF_nacimiento.setDate(rsEmpleado.getDate("F_nacimiento"));
                    jdCF_contratacion.setDate(rsEmpleado.getDate("F_contratacion"));
                    cmbSexo.setSelectedItem(rsEmpleado.getString("Sexo"));

                 
                    txtRut.setEnabled(true);
                    cmdBuscar.setEnabled(true);

                    // Bloquea 
                    txtNombre.setEnabled(false);
                    txtTelefono.setEnabled(false);
                    txtDescripcion.setEnabled(false);
                    txtDomicilio.setEnabled(false);
                    jdCF_nacimiento.setEnabled(false);
                    jdCF_contratacion.setEnabled(false);
                    cmbSexo.setEnabled(false);
                    cmdAceptar.setEnabled(false);
                } else {
 
                    txtNombre.setEnabled(true);
                    txtTelefono.setEnabled(true);
                    txtDescripcion.setEnabled(true);
                    txtDomicilio.setEnabled(true);
                    jdCF_nacimiento.setEnabled(true);
                    jdCF_contratacion.setEnabled(true);
                    cmbSexo.setEnabled(true);
                    cmdAceptar.setEnabled(true);

          
                    txtRut.setEnabled(false);

    
                    cmdBuscar.setEnabled(false);
                }

                rsEmpleado.close();
                pstmtBusquedaEmpleado.close();
                con.close();
            } catch (SQLException e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(this, "Error al buscar empleado: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "No se pudo establecer la conexión a la base de datos.");
}
        

        
        
    }//GEN-LAST:event_cmdBuscarActionPerformed

    private void txtRutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmCrearCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmCrearCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmCrearCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmCrearCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmCrearCuenta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbSexo;
    private javax.swing.JButton cmdAceptar;
    private javax.swing.JButton cmdBuscar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private com.toedter.calendar.JDateChooser jdCF_contratacion;
    private com.toedter.calendar.JDateChooser jdCF_nacimiento;
    private javax.swing.JTextArea txtDescripcion;
    private javax.swing.JTextField txtDomicilio;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtRut;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
