package Main;


import MantenedorEmpleado.frmEliminarE;
import MantenedorProducto.frmDeleProd;
import MantenedorProducto.frmModProducto;
import MantenedorProducto.frmProducto;
import frmEmpleado.frmEmplados;
import mantenedorOrdenTrab.frmOrdendeTrabajo;

import MantenedorEmpleado.frmActualizarE;
import MantenedorProducto.frmListarProducto;
import MantenedorTarea.frmDelTarea;
import MantenedorTarea.frmListarTarea;
import MantenedorTarea.frmTarea;
import MantenedorTarea.frmactualizarTarea;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Daniel
 */
public class frmPrincipal extends javax.swing.JFrame {
    private static frmPrincipal instanciaAnterior = null;


   

    /**
     * Creates new form frmPrincipal
     */
    public frmPrincipal() {
        initComponents();
 
        
        this.setLocationRelativeTo(null);
       habilitarComponentesSegunAcceso();

        
    }
    private static String tipoAcceso = "";
    public static void setTipoAcceso(String acceso) {
        tipoAcceso = acceso;
    }
    
    public void habilitarMnuMantenedor(boolean habilitado) {
        mnuMantenedor.setEnabled(habilitado);
    }
    
    public void  setmnuMantenedor(){
        this.mnuMantenedor.setEnabled(true);
    }
    
    public static void setInstanciaAnterior(frmPrincipal instancia) {
        instanciaAnterior = instancia;
    }
    
    public static frmPrincipal getInstanciaAnterior() {
        return instanciaAnterior;
    }
    private void habilitarComponentesSegunAcceso() {
    cmbPlanificacion.setEnabled(false);
    cmbOrden.setEnabled(false);
    //cmbEnlazar.setEnabled(false);
    cmdEmpleados.setEnabled(false);

    // Habilitar componentes según el tipo de acceso
    if ("Administrador".equals(tipoAcceso)) {
        cmbPlanificacion.setEnabled(true);
        cmbOrden.setEnabled(true);
        //cmbEnlazar.setEnabled(true);
        cmdEmpleados.setEnabled(true);
    } else if ("Costurero".equals(tipoAcceso)) {
        cmdEmpleados.setEnabled(true);
        // Debes quitar estos tres, ya que no están definidos en tu código
        // cmbPlanificacion.setEnabled(false);
        // cmbOrden.setEnabled(false);
        // cmbEnlazar.setEnabled(false);
        mnuMantenedor.setEnabled(false);
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        cmbOrden = new javax.swing.JButton();
        cmbPlanificacion = new javax.swing.JButton();
        cmdEmpleados = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu5 = new javax.swing.JMenu();
        mnuMantenedor = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jmUsuario = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem18 = new javax.swing.JMenuItem();
        jMenuItem19 = new javax.swing.JMenuItem();
        jMenuItem20 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenuItem15 = new javax.swing.JMenuItem();
        jMenuItem17 = new javax.swing.JMenuItem();
        jMenuItem16 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        mnuReporte = new javax.swing.JMenu();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        jMenuItem5.setText("jMenuItem5");

        jMenuItem9.setText("jMenuItem9");

        jMenuItem13.setText("jMenuItem13");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setModalExclusionType(null);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        jLabel5.setText("FABRICACIÓN DE PORTABEBÉS");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        jLabel4.setText("EN LA ");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, -1, -1));
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 40, -1, -1));

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText(" ACCEDER");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, 160, 40));

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        jLabel1.setText("SISTEMA DE SEGUIMIENTO");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        cmbOrden.setBackground(new java.awt.Color(255, 153, 0));
        cmbOrden.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        cmbOrden.setForeground(new java.awt.Color(255, 255, 255));
        cmbOrden.setText("ORDEN");
        cmbOrden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbOrdenActionPerformed(evt);
            }
        });
        jPanel3.add(cmbOrden, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 281, 160, 40));

        cmbPlanificacion.setBackground(new java.awt.Color(0, 0, 255));
        cmbPlanificacion.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        cmbPlanificacion.setForeground(new java.awt.Color(255, 255, 255));
        cmbPlanificacion.setText("PLANIFICACIÓN");
        cmbPlanificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbPlanificacionActionPerformed(evt);
            }
        });
        jPanel3.add(cmbPlanificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 331, 160, 40));

        cmdEmpleados.setBackground(new java.awt.Color(255, 153, 0));
        cmdEmpleados.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        cmdEmpleados.setForeground(new java.awt.Color(255, 255, 255));
        cmdEmpleados.setText("ASIGNACIÓN DE EMPLEADOS");
        cmdEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdEmpleadosActionPerformed(evt);
            }
        });
        jPanel3.add(cmdEmpleados, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, -1, 40));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com.imagenes/908pix.jpg"))); // NOI18N
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(487, 0, 200, 580));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 580));

        jMenu5.setText("Ordenes de trabajo");
        jMenu5.setEnabled(false);
        jMenuBar1.add(jMenu5);

        mnuMantenedor.setText("Mantenedores");
        mnuMantenedor.setEnabled(false);

        jMenu4.setText("Empleado");

        jMenuItem6.setText("Agregar");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem6);

        jMenuItem7.setText("Modificar");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem7);

        jMenuItem8.setText("Eliminar");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem8);

        jMenuItem10.setText("Consultar");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem10);

        jmUsuario.setText("Crear Usuario");
        jmUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmUsuarioActionPerformed(evt);
            }
        });
        jMenu4.add(jmUsuario);

        jMenuItem11.setText("Listar");
        jMenu4.add(jMenuItem11);

        mnuMantenedor.add(jMenu4);

        jMenuItem2.setText("Usuarios");
        mnuMantenedor.add(jMenuItem2);

        jMenu2.setText("Tarea");

        jMenuItem3.setText("Agregar");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuItem18.setText("Actualizar");
        jMenuItem18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem18ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem18);

        jMenuItem19.setText("Listar");
        jMenuItem19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem19ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem19);

        jMenuItem20.setText("Eliminar");
        jMenuItem20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem20ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem20);

        mnuMantenedor.add(jMenu2);

        jMenu1.setText("Producto");

        jMenuItem14.setText("Crear Producto");
        jMenuItem14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem14ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem14);

        jMenuItem15.setText("Actualizar Producto");
        jMenuItem15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem15ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem15);

        jMenuItem17.setText("Buscar Producto");
        jMenuItem17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem17ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem17);

        jMenuItem16.setText("Borrar Producto");
        jMenuItem16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem16ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem16);

        mnuMantenedor.add(jMenu1);

        jMenuItem4.setText("Insumos");
        mnuMantenedor.add(jMenuItem4);

        jMenuBar1.add(mnuMantenedor);

        mnuReporte.setText("Reporte");
        mnuReporte.setEnabled(false);

        jMenuItem12.setText("jMenuItem12");
        mnuReporte.add(jMenuItem12);

        jMenuBar1.add(mnuReporte);

        jMenu3.setText("Salir");

        jMenuItem1.setText("jMenuItem1");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem1);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        frmCrearCuenta Crear =  new frmCrearCuenta();
        Crear.setVisible(true);
        
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        frmActualizarE actualizar =new frmActualizarE();
        actualizar.setVisible(true);
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Login log = new Login();
        log.setVisible(true);
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jmUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmUsuarioActionPerformed
        frmUsuario Usuario = new frmUsuario();
        Usuario.setVisible(true);
    }//GEN-LAST:event_jmUsuarioActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
  
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        frmEliminarE eliminar = new frmEliminarE();
        eliminar.setVisible(true);
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem14ActionPerformed
        frmProducto FrmProducto = new frmProducto();
        FrmProducto.setVisible(true);
    }//GEN-LAST:event_jMenuItem14ActionPerformed

    private void jMenuItem16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem16ActionPerformed
       frmDeleProd FrmDele = new frmDeleProd();
       FrmDele.setVisible(true);
    }//GEN-LAST:event_jMenuItem16ActionPerformed

    private void jMenuItem15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem15ActionPerformed
       frmModProducto modificar = new frmModProducto();
       modificar.setVisible(true);
    }//GEN-LAST:event_jMenuItem15ActionPerformed

    private void cmbPlanificacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbPlanificacionActionPerformed
       frmPlanificacion planificacion = new frmPlanificacion();
       planificacion.setVisible(true);
    }//GEN-LAST:event_cmbPlanificacionActionPerformed

    private void cmbOrdenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbOrdenActionPerformed
       frmOrdendeTrabajo planificacion = new frmOrdendeTrabajo();
       planificacion.setVisible(true);
    }//GEN-LAST:event_cmbOrdenActionPerformed

    private void cmdEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdEmpleadosActionPerformed
        frmEmplados empleado = new frmEmplados();
        empleado.setVisible(true);
    }//GEN-LAST:event_cmdEmpleadosActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        frmTarea tarea = new frmTarea();
        tarea.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem18ActionPerformed
        frmactualizarTarea actualizar = new frmactualizarTarea();
        actualizar.setVisible(true);
    }//GEN-LAST:event_jMenuItem18ActionPerformed

    private void jMenuItem19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem19ActionPerformed
        frmListarTarea listar =new frmListarTarea();
        listar.setVisible(true);
    }//GEN-LAST:event_jMenuItem19ActionPerformed

    private void jMenuItem20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem20ActionPerformed
       frmDelTarea del = new frmDelTarea();
       del.setVisible(true);
    }//GEN-LAST:event_jMenuItem20ActionPerformed

    private void jMenuItem17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem17ActionPerformed
        frmListarProducto Listar = new frmListarProducto();
        Listar.setVisible(true);
    }//GEN-LAST:event_jMenuItem17ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
    System.exit(0);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               frmPrincipal instanciaAnterior = getInstanciaAnterior();
            
            // Crear una nueva instancia si no existe
            frmPrincipal formularioPrincipal;
            if (instanciaAnterior == null) {
                formularioPrincipal = new frmPrincipal();
                setInstanciaAnterior(formularioPrincipal);
            } else {
                formularioPrincipal = instanciaAnterior;
            }

            formularioPrincipal.habilitarComponentesSegunAcceso();
            formularioPrincipal.setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmbOrden;
    private javax.swing.JButton cmbPlanificacion;
    public javax.swing.JButton cmdEmpleados;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem17;
    private javax.swing.JMenuItem jMenuItem18;
    private javax.swing.JMenuItem jMenuItem19;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem20;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JMenuItem jmUsuario;
    private javax.swing.JMenu mnuMantenedor;
    private javax.swing.JMenu mnuReporte;
    // End of variables declaration//GEN-END:variables
}
