package Main;

import java.awt.event.ActionEvent;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.DefaultComboBoxModel;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import java.awt.event.ActionListener;
import java.util.List;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.DriverManager;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author vexer
 */
public class frmPlanificacion extends javax.swing.JFrame {
    
    /**
     * Creates new form frmPlanificacion
     */
    public frmPlanificacion() {
        initComponents();
        this.setLocationRelativeTo(null);
        llenarComboTarea();
        llenarComboEmpleado();
        llenarCombOrden();
        
    cmbOrden.addItemListener(new java.awt.event.ItemListener() {
        public void itemStateChanged(java.awt.event.ItemEvent evt) {
            cmbOrdenItemStateChanged(evt);
        }
    });
}
    
    public void llenarComboTarea() {
        try {
            cmbTarea.removeAllItems();

            String consulta = "SELECT NumTarea FROM Tarea";

            Connection con = Conexion.getConexion();
            java.sql.PreparedStatement pstmt = con.prepareStatement(consulta);

            ResultSet resultado = pstmt.executeQuery();
            while (resultado.next()) {
                String numTarea = resultado.getString("NumTarea");
                cmbTarea.addItem(numTarea);
            }

            resultado.close();
            pstmt.close();
            con.close();

        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    private void llenarComboEmpleado()
    {
        try{
            cmbEmpleado.removeAllItems();
            
            String consulta = "select nombre from empleado";
            
            Connection con = Conexion.getConexion();
            java.sql.PreparedStatement pstmt = con.prepareStatement(consulta);
            
            ResultSet resultado = pstmt.executeQuery();
            
            while (resultado.next()){
                String nombre = resultado.getString("nombre");
                cmbEmpleado.addItem(nombre);
            }
            
            resultado.close();
            pstmt.close();
            con.close();
        }catch(SQLException e){
            e.printStackTrace();
        }
    }
    
        private void llenarCombOrden() {
    try {
        cmbOrden.removeAllItems();

        // Establecer la conexión con la base de datos (ajustar la URL, usuario y contraseña)
        Connection con = Conexion.getConexion();

        String consulta = "SELECT NumOrden, Descripcion FROM OrdenTrabajo";
        try (PreparedStatement pst = con.prepareStatement(consulta)) {
            ResultSet rs = pst.executeQuery();
            while (rs.next()) {
                String numOrden = rs.getString("NumOrden");
                cmbOrden.addItem(numOrden);
            }
        }

        con.close();
    } catch (SQLException e) {
        e.printStackTrace();
    }
}
    private void cmbOrdenItemStateChanged(java.awt.event.ItemEvent evt) {
    if (evt.getStateChange() == java.awt.event.ItemEvent.SELECTED) {
        // Obtiene el número de orden seleccionado
        String numOrdenSeleccionado = cmbOrden.getSelectedItem().toString();

        try {
            // Establecer la conexión con la base de datos (ajustar la URL, usuario y contraseña)
            Connection con = Conexion.getConexion();

            // Consulta para obtener la descripción de la orden seleccionada
            String consulta = "SELECT Descripcion FROM OrdenTrabajo WHERE NumOrden = ?";
            try (PreparedStatement pst = con.prepareStatement(consulta)) {
                pst.setString(1, numOrdenSeleccionado);
                ResultSet rs = pst.executeQuery();

                if (rs.next()) {
                    String descripcion = rs.getString("Descripcion");

                    // Muestra la descripción en el campo de texto txtDescripcion
                    txtDescripcion.setText(descripcion);
                }
            }

            con.close();
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }
}
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblComboTarea = new javax.swing.JLabel();
        lblComboOrden1 = new javax.swing.JLabel();
        lblComboTarea1 = new javax.swing.JLabel();
        lblComboTarea2 = new javax.swing.JLabel();
        cmbOrden = new javax.swing.JComboBox<>();
        cmbEmpleado = new javax.swing.JComboBox<>();
        cmbTarea = new javax.swing.JComboBox<>();
        cmdVolver = new javax.swing.JButton();
        cmdIngresar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescripcion = new javax.swing.JTextArea();
        lblComboTarea3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        lblComboTarea.setText("Numero Tarea");

        lblComboOrden1.setText("Numero Orden:");

        lblComboTarea1.setText("Empleado");

        lblComboTarea2.setText("Avance");

        cmbEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbEmpleadoActionPerformed(evt);
            }
        });

        cmbTarea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTareaActionPerformed(evt);
            }
        });

        cmdVolver.setBackground(new java.awt.Color(255, 0, 0));
        cmdVolver.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        cmdVolver.setForeground(new java.awt.Color(255, 255, 255));
        cmdVolver.setText("Volver");
        cmdVolver.setBorder(null);
        cmdVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdVolverActionPerformed(evt);
            }
        });

        cmdIngresar.setBackground(new java.awt.Color(0, 0, 255));
        cmdIngresar.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        cmdIngresar.setForeground(new java.awt.Color(255, 255, 255));
        cmdIngresar.setText("Ingresar ");
        cmdIngresar.setBorder(null);
        cmdIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdIngresarActionPerformed(evt);
            }
        });

        txtDescripcion.setColumns(20);
        txtDescripcion.setRows(5);
        jScrollPane1.setViewportView(txtDescripcion);

        lblComboTarea3.setText("Descripcion de la orden");

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));

        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));

        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jLabel1.setText("PLANIFICACIÓN");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblComboTarea1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblComboTarea, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblComboOrden1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbTarea, javax.swing.GroupLayout.Alignment.LEADING, 0, 111, Short.MAX_VALUE)
                            .addComponent(cmbOrden, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbEmpleado, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator4, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmdVolver, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cmdIngresar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblComboTarea3, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(144, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lblComboTarea2)
                        .addGap(90, 90, 90))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(130, 130, 130))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblComboTarea2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblComboOrden1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cmbOrden, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(lblComboTarea3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(lblComboTarea)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbTarea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(lblComboTarea1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmdIngresar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmdVolver, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbTareaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTareaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbTareaActionPerformed

    private void cmbEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbEmpleadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbEmpleadoActionPerformed

    private void cmdVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdVolverActionPerformed
        this.dispose();
    }//GEN-LAST:event_cmdVolverActionPerformed

    private void cmdIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdIngresarActionPerformed
       String NumOrden = cmbOrden.getSelectedItem().toString();
    String NumTarea = cmbTarea.getSelectedItem().toString();
    String NombreEmpleado = cmbEmpleado.getSelectedItem().toString(); // Cambié la variable a NombreEmpleado para mayor claridad

    // Validación de Campos Obligatorios
    if (NumOrden.isEmpty() || NumTarea.isEmpty() || NombreEmpleado.isEmpty()) {
        System.out.println("Todos los campos son obligatorios. Verifique e inténtelo nuevamente.");
        return; // No continuar con la inserción
    }

    try {
        // Obtener el NumEmpleado del empleado seleccionado
        String sqlGetNumEmpleado = "SELECT NumEmpleado FROM Empleado WHERE Nombre = ?";
        try (Connection con = Conexion.getConexion();
             PreparedStatement pstmtGetNumEmpleado = con.prepareStatement(sqlGetNumEmpleado)) {

            pstmtGetNumEmpleado.setString(1, NombreEmpleado);
            ResultSet resultSet = pstmtGetNumEmpleado.executeQuery();

            if (resultSet.next()) {
                String NumEmpleado = resultSet.getString("NumEmpleado");

                // Inserción de Datos
                String sql = "INSERT INTO Planificacion (NumOrden, NumTarea, NumEmpleado) VALUES (?, ?, ?)";
                try (PreparedStatement pstmt = con.prepareStatement(sql)) {

                    pstmt.setString(1, NumOrden);
                    pstmt.setString(2, NumTarea);
                    pstmt.setString(3, NumEmpleado);

                    // Ejecutar la inserción
                    int filasAfectadas = pstmt.executeUpdate();
                    if (filasAfectadas > 0) {
                        System.out.println("Inserción exitosa.");
                    } else {
                        System.out.println("No se pudo insertar el registro.");
                    }
                }
            } else {
                System.out.println("No se encontró el NumEmpleado para el empleado seleccionado.");
            }
        }
    } catch (SQLException e) {
        e.printStackTrace();
    }
    }//GEN-LAST:event_cmdIngresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPlanificacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPlanificacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPlanificacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPlanificacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPlanificacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbEmpleado;
    private javax.swing.JComboBox<String> cmbOrden;
    private javax.swing.JComboBox<String> cmbTarea;
    private javax.swing.JButton cmdIngresar;
    private javax.swing.JButton cmdVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel lblComboOrden1;
    private javax.swing.JLabel lblComboTarea;
    private javax.swing.JLabel lblComboTarea1;
    private javax.swing.JLabel lblComboTarea2;
    private javax.swing.JLabel lblComboTarea3;
    private javax.swing.JTextArea txtDescripcion;
    // End of variables declaration//GEN-END:variables
}
